# Generated by Django 3.2.2 on 2022-02-22 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productimages'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductImages',
        ),
    ]
